[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = tests
addopts = -v

markers =
    smoke: Critical functionality tests
    regression: Existing functionality tests
    sanity: Specific functionality validation tests